# site settings
title: YEJIN KIM
subtitle: self-motivated & passionate
email: ay0119@yonsei.ac.kr
description: Deep Learning / Distributed Learning by Pytorch.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://0ptima1.github.io # the base hostname & protocol for your site
author:
#street_address: 1234 Somewhere Road
#city: Nashville
#state: TN
#zip_code: 55555
#country: United States of America
#phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/0ptima1
#  GitLab:
#  Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
#  Instagram:
#  LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#  Twitter: https://twitter.com/andrewbanchich
#  Facebook:
#  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md

